# Generated by Django 3.2.19 on 2023-07-01 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_blocked'),
        ('course', '0002_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseEntrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrolled_time', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrolled_course', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrolled_student', to='users.student')),
            ],
        ),
    ]
