# Generated by Django 3.2.19 on 2023-07-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_studentcourseentrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseentrollment',
            old_name='Course',
            new_name='course',
        ),
    ]
