# Generated by Django 3.2.19 on 2023-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_course_studentcourseentrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseentrollment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcourseentrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcourseentrollment',
            name='order_amount',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='studentcourseentrollment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentcourseentrollment',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
